name: Test

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/test-toolkit # Uses an action in the root directory




